on:  
  release:  
    types: [published]  

jobs:  
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          yarn install
          yarn clean
          yarn build
      - name: Upload macos binary file
        if: contains(${{ github.event.release.tag_name }}, "@shisama/package-b")  
        uses: actions/upload-release-asset@v1
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        with:  
          upload_url: ${{ github.event.release.upload_url }}  
          asset_path: ./packages/package-b/bin/node12-macos-x64  
          asset_name: macos
          asset_content_type: application/octet-stream
      - name: Upload linux binary file  
        if: contains(${{ github.event.release.tag_name }}, "@shisama/package-b")  
        uses: actions/upload-release-asset@v1  
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        with:  
          upload_url: ${{ github.event.release.upload_url }}  
          asset_path: ./packages/package-b/bin/node12-linux-x64  
          asset_name: linux
          asset_content_type: application/octet-stream
      - name: Upload windows binary file
        if: contains(${{ github.event.release.tag_name }}, "@shisama/package-b")  
        uses: actions/upload-release-asset@v1  
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        with:  
          upload_url: ${{ github.event.release.upload_url }}  
          asset_path: ./packages/package-b/bin/node12-win-x64  
          asset_name: win
          asset_content_type: application/octet-stream