on:  
  push:  
    tags:
      - '@shisama/package-b@*'

jobs:  
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          yarn install
          yarn clean
          yarn build
      - name: Set Version
        id: version
        run: echo "::set-output name=version::$(echo ${{ github.ref }} | cut -d'/' -f3)"
      - name: Upload macos binary file
        uses: actions/upload-release-asset@v1
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        with:  
          upload_url: ${{ github.ref }}  
          asset_path: ./packages/package-b/bin/package-b-macos
          asset_name: macos
          asset_content_type: application/octet-stream
      - name: Upload linux binary file
        uses: actions/upload-release-asset@v1
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        with:  
          upload_url: ${{ github.ref }}  
          asset_path: ./packages/package-b/bin/package-b-linux
          asset_name: linux
          asset_content_type: application/octet-stream
      - name: Upload win binary file
        uses: actions/upload-release-asset@v1
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        with:  
          upload_url: ${{ github.ref }}  
          asset_path: ./packages/package-b/bin/package-b-win.exe
          asset_name: win
          asset_content_type: application/octet-stream